### ISSUE TITLE
Fails to compile on g++ 14.1

### ISSUE THREAD

**Issue by Morilli** [preda/gpuowl#283]
Compiling with g++ 14.1 results in the following error:
```
src/tune.cpp: In function 'void tune(Queue*, GpuCommon)':
src/tune.cpp:211:8: error: 'sort' is not a member of 'std'; did you mean 'sqrt'?
  211 |   std::sort(results.begin(), results.end());
      |        ^~~~
      |        sqrt
make: *** [Makefile:57: build-release/tune.o] Error 1
```

Compilation is fine on 13.2, so I assume some standard library headers previously included `algorithm` themselves but no longer do on 14.1.

**Comment by preda** [comment]
Thanks, fixed now.
